test: "hello"
int: 1
double: 2.0
vector: [1.0, 2.0, 3.0, 4.0, 5.0]
matrix:
  rows: 4
  cols: 4
  data: [
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0
  ]
