settings:
  cam0_image_path: "/data/euroc_mav/cam_april/mav0/cam0/data"
  cam1_image_path: "/data/euroc_mav/cam_april/mav0/cam1/data"
  cam0_preprocess_path: "/data/euroc_mav/cam_april/mav0/aprilgrid0/cam0/data"
  cam1_preprocess_path: "/data/euroc_mav/cam_april/mav0/aprilgrid0/cam1/data"
  results_file: "/data/euroc_mav/cam_april/calib.yaml"

calib_target:
  target_type: 'aprilgrid'  # Target type
  tag_rows: 6               # Number of rows
  tag_cols: 6               # Number of cols
  tag_size: 0.085           # Size of apriltag, edge to edge [m]
  tag_spacing: 0.3          # Ratio of space between tags to tagSize
                            # Example: tagSize=2m, spacing=0.5m
                            # --> tagSpacing=0.25[-]

cam0:
  resolution: [752, 480]
  lens_hfov: 98.0
  lens_vfov: 73.0
  camera_model: "pinhole"
  distortion_model: "radtan"

cam1:
  resolution: [752, 480]
  lens_hfov: 98.0
  lens_vfov: 73.0
  camera_model: "pinhole"
  distortion_model: "radtan"
