calib:
  target_file: "/data/configs/aprilgrid_6x6.yaml"
  image_path: "/data/marker_calib/cam0/data"
  preprocess_path: "/data/marker_calib/aprilgrid0/data"
  imshow: true

cam0:
  resolution: [640, 480]
  lens_hfov: 90.0
  lens_vfov: 90.0
  camera_model: "pinhole"
  distortion_model: "radtan"
