calib:
  target_file: "config/aprilgrid_6x6.yaml"
  image_path: "/data/sync_data/cam0/data"
  preprocess_path: "/data/sync_aprilgrid_data"
  estimate_target: true
  imshow: true

cam0:
  camera_model: "pinhole"
  distortion_model: "radtan"
  resolution: [640.000000, 480.000000]
  intrinsics: [618.292623, 619.719100, 328.796312, 236.726813]
  distortion: [0.098084, -0.124203, -0.001879, 0.001630]
