# calib:
#   target_file: "config/aprilgrid_6x6.yaml"
#   image_path: "/data/euroc_mav/cam_april/mav0/cam0/data/"
#   preprocess_path: "/data/euroc_mav/cam_april/aprilgrid"
#   estimate_target: true
#   imshow: true
#
# cam0:
#   resolution: [752, 480]
#   camera_model: "pinhole"
#   distortion_model: "radtan"
#   intrinsics: [458.654, 457.296, 367.215, 248.375]
#   distortion: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]


calib:
  target_file: "config/aprilgrid_6x6.yaml"
  image_path: "/data/euroc_mav/imu_april/mav0/cam0/data/"
  preprocess_path: "/data/euroc_mav/imu_april/aprilgrid/cam0"
  estimate_target: true
  imshow: true

cam0:
  resolution: [752, 480]
  camera_model: "pinhole"
  distortion_model: "radtan"
  intrinsics: [458.654, 457.296, 367.215, 248.375]
  distortion: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]

# cam0:
#   camera_model: "pinhole"
#   distortion_model: "radtan"
#   resolution: [640.000000, 480.000000]
#   intrinsics: [618.292623, 619.719100, 328.796312, 236.726813]
#   distortion: [0.098084, -0.124203, -0.001879, 0.001630]
