calib:
  target_file: "config/aprilgrid_6x6.yaml"
  image_path: "/data/calibration_target/cam0/data"
  imshow: true

cam0:
  resolution: [640, 480]
  camera_model: "pinhole"
  distortion_model: "radtan"
  intrinsics: [630.043222, 630.362170, 327.615743, 238.386901]
  distortion: [0.139066, -0.349607, -0.000163,0.003016]
