name: ci
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: make third_party

    - name: Build libproto
      run: make build

    - name: Build tests
      run: make tests

    - name: Run tests
      run: make run_test_proto
