name: ci
on: [push]
jobs:
  build_proto:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: make deps

    - name: Build libproto
      run: make release

    - name: Run tests
      run: make run_tests

    # - name: Build ROS interface
    #   run: make ros
